// This file will be auto-generated by Supabase CLI
// For now, we'll use a basic type definition

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            user_profiles: {
                Row: {
                    id: string
                    email: string
                    full_name: string
                    avatar_url: string | null
                    role: 'admin' | 'teacher' | 'student'
                    is_active: boolean
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id: string
                    email: string
                    full_name: string
                    avatar_url?: string | null
                    role: 'admin' | 'teacher' | 'student'
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    email?: string
                    full_name?: string
                    avatar_url?: string | null
                    role?: 'admin' | 'teacher' | 'student'
                    is_active?: boolean
                    created_at?: string
                    updated_at?: string
                }
            }
            courses: {
                Row: {
                    id: string
                    name: string
                    code: string
                    description: string | null
                    teacher_id: string
                    created_at: string
                    updated_at: string
                }
                Insert: {
                    id?: string
                    name: string
                    code: string
                    description?: string | null
                    teacher_id: string
                    created_at?: string
                    updated_at?: string
                }
                Update: {
                    id?: string
                    name?: string
                    code?: string
                    description?: string | null
                    teacher_id?: string
                    created_at?: string
                    updated_at?: string
                }
            },
            enrollments: {
                Row: {
                    id: string
                    course_id: string
                    student_email: string
                    status: 'invited' | 'active'
                    enrolled_at: string
                }
                Insert: {
                    id?: string
                    course_id: string
                    student_email: string
                    status: 'invited' | 'active'
                    enrolled_at?: string
                }
                Update: {
                    id?: string
                    course_id?: string
                    student_email?: string
                    status?: 'invited' | 'active'
                    enrolled_at?: string
                }
            },
            documents: {
                Row: {
                    id: number
                    title: string
                    content: string
                    metadata: Json | null
                    course_id: string | null
                    created_at: string
                }
                Insert: {
                    id?: number
                    title: string
                    content: string
                    metadata?: Json | null
                    course_id?: string | null
                    created_at?: string
                }
                Update: {
                    id?: number
                    title?: string
                    content?: string
                    metadata?: Json | null
                    course_id?: string | null
                    created_at?: string
                }
            },
            student_profiles: {
                Row: {
                    id: string
                    student_code: string
                    enrollment_date: string
                    current_semester: number | null
                    gpa: number
                    total_credits_approved: number
                    status: 'active' | 'inactive' | 'graduated' | 'suspended'
                }
                Insert: {
                    id: string
                    student_code: string
                    enrollment_date: string
                    current_semester?: number | null
                    gpa?: number
                    total_credits_approved?: number
                    status?: 'active' | 'inactive' | 'graduated' | 'suspended'
                }
                Update: {
                    id?: string
                    student_code?: string
                    enrollment_date?: string
                    current_semester?: number | null
                    gpa?: number
                    total_credits_approved?: number
                    status?: 'active' | 'inactive' | 'graduated' | 'suspended'
                }
            }
            // Add more table types as we create them
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            user_role: 'admin' | 'teacher' | 'student'
            student_status: 'active' | 'inactive' | 'graduated' | 'suspended'
        }
    }
}
